### ISSUE TITLE
URL is Invalid

### ISSUE THREAD

**Issue by mdewolfe** [foursquare/FSNetworking#1]
I am trying to integrate FSNetworking into my application.  When I debug `[FSNConnection start]`, I see the URL is invalid and I get the error "message sent to deallocated instance." When printed, I get:
`(lldb)po self.url
(NSURL *) $4 = 0x07e81150 [no Objective-C description available]`.  The `NSAssert(self.url, @"nil url")` passes, I am guessing this is a dangling pointer.

My project is compiled with ARC enabled, and I set -fno-objc-arc as suggested in the readme file.

**Comment by bryanbonczek** [comment]
Hi Mike,

Sorry about your troubles. It just so happens that FSNetworking was converted to ARC a couple of months ago. Can you try removing the -fno-objc-arc and see if the problem still persists? I'll also update the documentation to reflect this change.

Bryan

**Comment by mdewolfe** [comment]
Thank you, removing `-fno-objc-arc` fixed the issue.  There was still one call to `[super dealloc]` in `[FSNConnection dealloc]`.  Easily fixed though, I guess that line did not get pushed.

**Comment by bryanbonczek** [comment]
Great. Glad it fixed your issue. 

Also, it looks like the latest version of FSNConnection.m doesn't include `[super dealloc]`. Can you make sure you have the latest code?

**Comment by mdewolfe** [comment]
Will do.
