### ISSUE TITLE
Please pull in additional refactors in the outstanding pull request.

### ISSUE THREAD

**Issue by gwk** [foursquare/FSNetworking#10]
There is stuff accumulating in my fork that i would like to see upstream; most recently I did a small refactor of adam's isAcceptableValue changes and he asked me to open an issue. It is all very straightforward stuff.

My change set does not fix the missing NSArray urlEncodedString implementation, but it does add one for NSNumber that replaces the old inlined conditional logic. 

Thanks! -g

**Comment by adamalix** [comment]
Fixed with this commit

c55651c86293f8415a57aa9e0e720c2311e820b7
