### ISSUE TITLE
FSNData and Straight C Code

### ISSUE THREAD

**Issue by mdewolfe** [foursquare/FSNetworking#17]
I am adding a few things to FSNData, and I would like to know the why straight C code was used for `NSString *stringForMimeType(MimeType type);` over a class level method. Is it a preferred style, or some other reason?

**Comment by gwk** [comment]
This is a minor stylistic preference, based on the fact that MimeType is an enum, not an Obj-C class. I think you are suggesting the alternative class method on FSNData:
- (NSString *)stringForMimeType:(MimeType)type;
  calls would look like this:
  [FSNData stringForMimeType:type];
  The method call is more verbose, and it makes unnecessary use of message dispatch. Also, the association with FSNData is arbitrary; stringForMimeType could be useful independently of the rest of the code.
  All of these are very minor points of course, but that's my reasoning. Thanks for asking :)

**Comment by mdewolfe** [comment]
@gwk Thanks. I asking mostly for curiosity, but also I am trying to follow the general style that is already there.
