### ISSUE TITLE
Since not too much activity in FSNetworking,....

### ISSUE THREAD

**Issue by gordemota** [foursquare/FSNetworking#3]
Since not too much activity in FSNetworking, probably using AFNetworking with better support a better idea

**Comment by mdewolfe** [comment]
I disaggree.  FSNetworking has enough functionality.  Also, I find its simplicity easy to work with.

**Comment by lassic** [comment]
I use it too, very good lightweight library and easily extendable.
The author was also very helpful with questions and added small features that I requested.

**Comment by mdewolfe** [comment]
They are very good at responding to questions and issues.

**Comment by gordemota** [comment]
that's great news. Just want to make sure it is still supported before I am using it. Since right now every body using AFNetworking as a Standard

Thanks

**Comment by jansichermann** [comment]
It's very much still supported!!

**Comment by mdewolfe** [comment]
@jansichermann Is it safe to assume you are referring to FSNetworking?  I hope so because it has made things much more simple for me. Also because I have a few small contributions that are being prepped.

**Comment by bryanbonczek** [comment]
Hey guys,

Thanks for your continued interest in FSNetworking. While we haven't committed anything new in quite awhile, the library is very much active and in use in our production iOS app. Any improvements that we make will definitely be shared with the community. If you are having a particular problem with the existing code, or you feel that it is missing a particular piece of functionality, feel free to open up a github issue and we'll have a look. Bug fixes and pull requests are also welcome!

Thanks,

Bryan

**Comment by mdewolfe** [comment]
Do you guys have coding guidelines?

**Comment by bryanbonczek** [comment]
Nothing specific. Try your best to mimic the style of the rest of the code. If anything stands out as being off, we can resolve it at pull request time.

**Comment by gwk** [comment]
I have one high-level comment about the library design: We avoid requiring subclassing by making extensive use of blocks. In general I find this to be desirable because I don't run into cases where subclass implementations (e.g. between GET and POST) become mutually conflicting when I want to add new functionality.

If you find yourself needing to subclass FSNConnection you may be adding unnecessary complexity or misunderstanding the standard usage pattern; feel free to ask questions if you have any trouble!

**Comment by mdewolfe** [comment]
I agree entirely.  FSNetworking seems so far to be the cleanest networking library I have researched, and will probably integrate it in the new year; we are using ASIHTTPRequest(!).
